language: c
sudo: required

env:
  - OCAML_VERSION=4.09 POST_INSTALL_HOOK="opam install dune odoc; dune build @doc; cp -r _build/default/_doc/_html/ result/"
os:
  - linux

install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh

script:
  - bash -ex .travis-opam.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: result/
  on:
    branch: master
    condition: "$OCAML_VERSION = 4.09"